name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildWindows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install -y mingw-w64
        make win64
        make win32
    - name: upload win64
      uses: actions/upload-artifact@v3.1.0
      with:
          name: windows-x86_64
          path: |
            GetBitches-win64.exe
    - name: upload win32
      uses: actions/upload-artifact@v3.1.0
      with:
          name: windows-x86
          path: |
            GetBitches-win32.exe
  buildLinux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo add-apt-repository ppa:apt-fast/stable
        sudo apt-get -y install apt-fast
        sudo apt-fast install gcc-multilib-powerpc-linux-gnu gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-mips-linux-gnu gcc-multilib-i686-linux-gnu gcc-9-multilib gcc-riscv64-linux-gnu -y
        make all -j4
        sudo chmod +x *.out
        make package
    - name: upload x86_64
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-amd64
          path: |
            Linux-amd64.tar.gz
    - name: upload i386
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-i386
          path: |
            Linux-i386.tar.gz
    - name: upload raspi
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-raspi
          path: |
            Linux-raspi.tar.gz
    - name: upload aarch64
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-aarch64
          path: |
            Linux-aarch64.tar.gz
    - name: upload PPC
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-PPC
          path: |
            Linux-PPC.tar.gz
    - name: upload MIPS
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-MIPS
          path: |
            Linux-MIPS.tar.gz
    - name: upload RISCV
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-RISCV
          path: |
            Linux-RISCV.tar.gz
  buildMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: make mac
    - name: upload
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Mac-build
          path: |
            *.app
