name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildWindows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install -y mingw-w64
        make windows
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: windows-build
          path: |
            *.exe
  buildLinux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install gcc-multilib-powerpc-linux-gnu gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-mips-linux-gnu gcc-multilib-i686-linux-gnu gcc-9-multilib gcc-riscv64-linux-gnu  musl -y
        make linux
        make raspi
        make aarch64
        make i386
        make ppc
        make riscv
        make mips
        sudo chmod 755 *.out
    - name: upload x86_64
      uses: actions/upload-artifact@v3
      with:
          name: Linux-amd64
          path: |
            GetBitches.out
    - name: upload i386
      uses: actions/upload-artifact@v3
      with:
          name: Linux-i386
          path: |
            GetBitches-i386.out
    - name: upload raspi
      uses: actions/upload-artifact@v3
      with:
          name: Linux-raspi
          path: |
            GetBitches-raspi.out
    - name: upload aarch64
      uses: actions/upload-artifact@v3
      with:
          name: Linux-aarch64
          path: |
            GetBitches-aarch64.out
    - name: upload PPC
      uses: actions/upload-artifact@v3
      with:
          name: Linux-PPC
          path: |
            GetBitches-PowerPC.out
    - name: upload MIPS
      uses: actions/upload-artifact@v3
      with:
          name: Linux-MIPS
          path: |
            GetBitches-MIPS.out
    - name: upload RISCV
      uses: actions/upload-artifact@v3
      with:
          name: Linux-RISCV
          path: |
            GetBitches-RISCV.out
  buildMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: make mac
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: Mac-build
          path: |
            *.app
