name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildWindows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install -y mingw-w64
        cd c
        wget https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-mingw.tar.gz
        tar -xvf ./SDL2_mixer-devel-2.6.2-mingw.tar.gz
        cd SDL2_mixer-devel-2.6.2
        sudo make install-package arch=x86_64-w64-mingw32 prefix=/usr
        cd ..
        wget https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-2.6.2.zip
        unzip SDL2_mixer-2.6.2.zip
        make win64-sdl
        make win32
    - name: upload win64
      uses: actions/upload-artifact@v3.1.0
      with:
          name: windows-x86_64
          path: |
            GetBitches-win64.exe
            res
            *.dll
    - name: upload win32
      uses: actions/upload-artifact@v3.1.0
      with:
          name: windows-x86
          path: |
            GetBitches-win32.exe
  buildamd64:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev
        cd c
        make linux
        sudo chmod +x *.out
        tar -czvf Linux-amd64.tar.gz GetBitches.out res
    - name: upload x86_64
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-amd64
          path: |
            Linux-amd64.tar.gz
  buildi386:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |        
        sudo add-apt-repository ppa:apt-fast/stable
        sudo apt-get -y install apt-fast
        sudo apt-fast install gcc-9-multilib-i686-linux-gnu gcc-9-multilib gcc-9 -y
        cd c
        make i386
        sudo chmod +x *.out
        tar -czvf Linux-i386.tar.gz GetBitches-i386.out
    - name: upload i386
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-i386
          path: |
            Linux-i386.tar.gz
  buildraspi:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt-get -y install gcc-arm-linux-gnueabihf gcc-9-arm-linux-gnueabihf gcc-9-multilib gcc-9
        cd c
        make raspi
        sudo chmod +x *.out
        tar -czvf Linux-raspi.tar.gz GetBitches-raspi.out
    - name: upload raspi
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-raspi
          path: |
            Linux-raspi.tar.gz

  buildaarch64:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt-get -y install gcc-aarch64-linux-gnu gcc-9-aarch64-linux-gnu gcc-9-multilib gcc-9
        cd c
        make aarch64
        sudo chmod +x *.out
        tar -czvf Linux-aarch64.tar.gz GetBitches-aarch64.out
    - name: upload aarch64
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-aarch64
          path: |
            Linux-aarch64.tar.gz

  buildPPC:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt-get -y install gcc-multilib-powerpc-linux-gnu gcc-9-multilib gcc-9
        cd c
        make ppc
        sudo chmod +x *.out
        tar -czvf Linux-PPC.tar.gz GetBitches-PowerPC.out
    - name: upload PPC
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-PPC
          path: |
            Linux-PPC.tar.gz

  buildMIPS:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt-get -y install gcc-mips-linux-gnu gcc-9-multilib gcc-9
        cd c
        make mips
        sudo chmod +x *.out
        tar -czvf Linux-MIPS.tar.gz GetBitches-MIPS.out
    - name: upload MIPS
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-MIPS
          path: |
            Linux-MIPS.tar.gz

  buildRISCV:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt-get -y install gcc-riscv64-linux-gnu gcc-9-multilib gcc-9
        cd c
        make riscv
        sudo chmod +x *.out
        tar -czvf Linux-RISCV.tar.gz GetBitches-RISCV.out
    - name: upload RISCV
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Linux-RISCV
          path: |
            Linux-RISCV.tar.gz

  buildMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: cd c && make mac
    - name: upload
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Mac-build
          path: |
            *.app