name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildWindows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install -y mingw-w64
        make win64
        make win32
    - name: upload win64
      uses: actions/upload-artifact@v3
      with:
          name: windows-x86_64
          path: |
            GetBitches-win64.exe
    - name: upload win32
      uses: actions/upload-artifact@v3
      with:
          name: windows-x86
          path: |
            GetBitches-win32.exe
  buildLinux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install gcc-multilib-powerpc-linux-gnu gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-mips-linux-gnu gcc-multilib-i686-linux-gnu gcc-9-multilib gcc-riscv64-linux-gnu  musl -y
        make linux
        make raspi
        make aarch64
        make i386
        make ppc
        make riscv
        make mips
        sudo chmod +x *.out
        make package
    - name: upload x86_64
      uses: actions/upload-artifact@v3
      with:
          name: Linux-amd64
          path: |
            Linux.zip
    - name: upload i386
      uses: actions/upload-artifact@v3
      with:
          name: Linux-i386
          path: |
            Linux-i386.zip
    - name: upload raspi
      uses: actions/upload-artifact@v3
      with:
          name: Linux-raspi
          path: |
            Linux-raspi.zip
    - name: upload aarch64
      uses: actions/upload-artifact@v3
      with:
          name: Linux-aarch64
          path: |
            Linux-aarch64.zip
    - name: upload PPC
      uses: actions/upload-artifact@v3
      with:
          name: Linux-PPC
          path: |
            Linux-PowerPC.zip
    - name: upload MIPS
      uses: actions/upload-artifact@v3
      with:
          name: Linux-MIPS
          path: |
            Linux-MIPS.zip
    - name: upload RISCV
      uses: actions/upload-artifact@v3
      with:
          name: Linux-RISCV
          path: |
            Linux-RISCV.zip
  buildMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: make mac
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: Mac-build
          path: |
            *.app
