name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildWindows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: |
        sudo apt install -y mingw-w64
        make windows
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: windows-build
          path: |
            *.exe
  buildLinux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: make linux
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: Linux-build
          path: |
            *.out
  buildMac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    #- name: configure
    #  run: ./configure
    - name: make
      run: make mac
    - name: upload
      uses: actions/upload-artifact@v3
      with:
          name: Mac-build
          path: |
            *.app
